### ISSUE TITLE
ԓ/л

### ISSUE THREAD

**Issue by BasilisAndr** [BasilisAndr/chkchn#4]
1) The Uniparser dictionary doesn't have the ԓ letter at all
2) The grammar and Michael's script say that the letters are fully interchangeable
3) The ckt.crp.txt has both letters in similar contexts:
ӄолейӈын
гантоԓен
@evoling Is this some inconsistency in the corpus or are they not fully interchangeable? Is it ok to just stick to one variant? And if so, @ftyers is it possible to turn, say, ԓ:л in all contexts in analysis but not turn л:ԓ in generation?

**Comment by ftyers** [comment]
As far as I know when dealing with Chukchi we should just change all л to ԓ in the corpus. I imagine any difference is an OCR error or typo. We should be able to deal with both in analysis (but for the moment I would suggest just changing the corpus.) Let's see what @evoling thinks before going ahead though.

**Comment by evoling** [comment]
They are fully interchangeable -- the symbol was invented recently as a wholesale replacement of "Russian" л. I agree with Fran, the correct thing to do is to change all л to ԓ.

**Comment by BasilisAndr** [comment]
Great, thanks!
