### ISSUE TITLE
reduplication?

### ISSUE THREAD

**Issue by BasilisAndr** [BasilisAndr/chkchn#5]
I've been looking through the nouns lexicon and found several words there that look like reduplication, but were written as Ia in the dictionary. Here's the list of what I could find:

ԓеԓеԓ     ! роса
ԓигԓиг     ! яйцо (птичье)
ԓиԓиԓ     ! 1) жёԓчь; 2) жёлчный пузырь
ԓинԓиӈ     ! сердце
мормор     ! 1) соприкасающаяся с земԓёй часть ступни; 2) край ладони
тамтам     ! 1) шишка; 2) бородавка
тавтав     ! лай
рытрыт     ! (2) 1) жила (как материал для шитья); 2) сухожилие; 3) пряжа
киԓкиԓ     ! пуп
кымкым     ! 1) колбаса из оленьего мяса; 2) круглый предмет
кыткыт     ! (2) поздняя весна
кэвкэв     ! 1) хрящ; 2) дыхательное горло
кэвкэв     ! печенье
кэркэр     ! меховой женский комбинезон
ӄоӈӄоӈ     ! бубенчик, колокольчик
ӄыԓӄыԓ     ! 1) нерешительность; 2) леность
ԓьувԓьув     ! 1) силок; 2) петля
мымыԓ     ! вошь
мэԓмэԓ     ! хорошая погода
нымным     ! селение
ӈыԓгыԓ     ! (2) дым
омом     ! тепло, жара
очоч     ! начальник
пиӈпиӈ     ! 1) пепел, зола; 2) пыль; 3) порох; 4) порошок
пъоӈпъоӈ     ! гриб
рытрыт     ! (2) 1) жила (как материал для шитья); 2) сухожилие; 3) пряжа
черычер     ! глина
чотчот     ! 1) изголовье; 2) подушка
чувчув     ! кровоподтёк
ыӄыӄ     ! стужа
ымым     ! 1) прилив; 2) прибыль воды
ыӈыӈ     ! * клей
эӈэӈ     ! * лекарство
мыймый     ! (2)  съедобный корень

Is all of this actually reduplication?

**Comment by ftyers** [comment]
Even if it is, I think we should treat reduplication in the lexicon, not in the phonological rules. It will simplify things a lot.

**Comment by BasilisAndr** [comment]
Of course, but if it stays as it is all the obl forms would be formed from
reduplicated stems
lør. 10. jun. 2017 kl. 15.00 skrev Francis Tyers <notifications@github.com>:

**Comment by evoling** [comment]
There are tests to tell: some of them are definitely reduplication (omom "warmth", n-om-qen "it is warm", om-əcʔaw- "feel warm", om-aw- "warm up (smth)"). If I had to guess I would say they are almost all reduplication, but most of them I simply don't know for sure. It would be pretty hard to find out without doing fieldwork.

The connection between oblique stems and the absolutive form is pretty irregular, so I guess it has to be in the lexicon anyway.
